config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'expenses/new'
  get 'expenses/index'
  get 'expenses/create'
  get 'expenses/show'
  devise_for :users
  root 'splash#home'
  resources :users do
    resources :categories, only: [:index, :show, :new, :create]
    resources :expenses, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_expenses, dependent: :destroy

  def total_price
    ce = category_expenses.where(self == :category)
    total = 0
    ce.each do |record|
      total += Expense.find(record.expense_id).amount
    end
    total.to_f
  end
end

app/models/category_expense.rb
class CategoryExpense < ApplicationRecord
  belongs_to :category
  belongs_to :expense
end

app/models/expense.rb
class Expense < ApplicationRecord
  has_many :category_expenses, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :full_name, presence: true
  has_many :categories, dependent: :destroy
  has_many :expenses, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    user_categories_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  def index
    @categories = current_user.categories.order(created_at: :desc)
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.find(params[:id])
    category_expenses = Category.find(params[:id]).category_expenses.reverse
    @expenses = []
    category_expenses.each do |ce|
      @expenses << ce.expense
    end
  end

  # GET /categories/new
  def new
    @category = Category.new
    @category.user = current_user
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = current_user

    if @category.save
      redirect_to user_categories_path(current_user)
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def new
    @expense = Expense.new
    @category_expense = CategoryExpense.new
  end

  def create
    @expense = Expense.new(expense_params)
    @expense.user = current_user
    if @expense.save
      ce = CategoryExpense.new(category_id: params[:expense][:category], expense_id: @expense.id)
      if ce.save
        redirect_to user_categories_path(current_user), notice: 'The expense was successfully added.'
      else

        render plain: ce.errors.full_messages
      end

    else
      render :new
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount)
  end

  def category_params
    params.require(:expense).permit(:category)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def home; end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/categories/index.html.erb
<%= render 'layouts/header', msg: 'List of all categories', btn: 'Home' %>
<% if @categories.empty? %>
  <%= render 'layouts/alert', msg: 'There is not any category yet.', class_name: 'primary' %>
<% end %>

<ul class="list-group mb-auto">
  <% @categories.each do |item| %>
    <li class="list-group-item my-2 border">
      <div class="row align-items-center">
        <div class="col-3 ">
          <img src="<%= item.icon %>" alt="
          <% item.icon %>" class="img-thumbnail rounded-circle">
        </div>
        <div class="col-6">
          <h3 class="mb-4">
            <%= link_to item.name, user_category_path(current_user, item), class: 'link-dark text-decoration-none' %></h3>
          <span class="text-muted"><%= item.created_at %></span>
        </div>
        <div class="col-3 text-center">$<strong><%= item.total_price %></strong></div>
      </div>
    </li>
  <% end %>
</ul>
<div class="btn-container">
  <%= link_to 'Add new category', new_user_category_path(current_user), class: 'custom-btn' %>
</div>

app/views/categories/new.html.erb
<%= render 'layouts/header', msg: 'Add New Category', btn: '<' %>
<div class="form d-flex flex-column ">
  <%= form_with(model: @category, url: user_categories_path(current_user), method: :post) do |form| %>
    <div class="my-3">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>
    <div class="my-3">
      <%= form.label :icon, "Icon (paste the url of your icon)" %>
      <%= form.text_field :icon, class: 'form-control' %>
    </div>
    <div class="my-3 mt-auto  btn-container fixed-bottom">
      <%= form.submit class: 'custom-btn' %>
    </div>
  <% end %>
</div>

app/views/categories/show.html.erb
<%= render 'layouts/header', msg: "All expenses for \"#{@category.name}\"" + @category.name, btn: '<' %>
<% if @expenses.empty? %>
  <%= render 'layouts/alert', msg: 'There is not any expense for this category yet.', class_name: 'primary' %>
<% end %>

<div class="d-flex justify-content-between my-3 align-items-center bg-body text-muted p-3">
  <strong>Total expenses: </strong>
  <p class="m-0 fw-bold text-muted">$<%=@category.total_price %></p>
</div>

<ul class="list-group">
  <% @expenses.each do |item| %>
    <li class="list-group-item my-2 border">
      <div class="row align-items-center">
        <div class="col-9">
          <h3 class="mb-4">
            <%= item.name %></h3>
          <span class="text-muted"><%= item.created_at %></span>
        </div>
        <div class="col-3 text-center">$<strong><%= item.amount %></strong></div>
      </div>
    </li>
  <% end %>
</ul>
<div class="btn-container mt-auto">
  <%= link_to 'Add new expense', new_user_expense_path(current_user), class: 'custom-btn' %>
</div>

app/views/expenses/index.html.erb
<h1>Expenses#index</h1>
<p>Find me in app/views/expenses/index.html.erb</p>

app/views/expenses/new.html.erb
<%= render 'layouts/header', msg: 'Add New Expense', btn: '<' %>
<%= form_with(model: @expense, url: user_expenses_path(current_user), method: :post) do |form| %>
  <div class="my-3">
    <%= form.label :name, 'What for' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="my-3">
    <%= form.label :amount %>
    <%= form.number_field :amount, class: 'form-control' %>
  </div>
  <div class="my-3">
    <%= form.label :category, 'Category(Select one option)' %>
    <%= form.select :category, Category.all.map { |c| [c.name, c.id] }, {}, { class: 'form-control' } %>
  </div>
  <div class="btn-container mt-auto fixed-bottom">
    <%= form.submit class: 'custom-btn' %>
  </div>
<% end %>

app/views/expenses/show.html.erb
<h1>Expenses#show</h1>
<p>Find me in app/views/expenses/show.html.erb</p>

app/views/layouts/_alert.html.erb
<div class="alert alert-<%= class_name %> alert-dismissible fade show" role="alert">
  <%= msg %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_header.html.erb
<div class="text-bg-primary p-4 d-flex align-items-center gap-2 mb-2">
  <%= link_to btn, user_categories_path(current_user), class: 'btn btn-primary fw-bold' %>
  <h4 class="m-0"><%= msg %></h4>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExpenseManagement</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
</head>

<body>
<div class="container d-flex flex-column min-vh-100 py-2 bg-light">
  <% if notice %>
    <%= render 'layouts/alert', msg: notice, class_name: 'warning' %>
  <% end %>
  <% if alert %>
    <%= render 'layouts/alert', msg: alert, class_name: 'danger' %>
  <% end %>
  <%= yield %>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

app/views/splash/home.html.erb
<div class="text-center pt-5 d-flex flex-column justify-content-center min-vh-100">
  <h1 class="fw-bold mb-5">Welcome to <br>Expense Management <br>Application</h1>
  <div class="mt-auto fixed-bottom">
    <%= link_to 'Log in', new_user_session_path, class: 'log-in  d-block text-decoration-none rounded' %>
    <%= link_to 'Sign up', new_registration_path(:user), class: 'sign-in d-block text-decoration-none rounded' %>
  </div>
</div>